// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unused_field, unnecessary_non_null_assertion, dead_code
library trafilatura_uniffi;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'dart:typed_data';

final class _UniFfiFfiBufferElement extends ffi.Union {
  @ffi.Uint8()
  external int u8;

  @ffi.Int8()
  external int i8;

  @ffi.Uint16()
  external int u16;

  @ffi.Int16()
  external int i16;

  @ffi.Uint32()
  external int u32;

  @ffi.Int32()
  external int i32;

  @ffi.Uint64()
  external int u64;

  @ffi.Int64()
  external int i64;

  @ffi.Float()
  external double float32;

  @ffi.Double()
  external double float64;

  external ffi.Pointer<ffi.Void> ptr;
}

final class _UniFfiRustBuffer extends ffi.Struct {
  @ffi.Uint64()
  external int capacity;

  @ffi.Uint64()
  external int len;

  external ffi.Pointer<ffi.Uint8> data;
}

final class _UniFfiForeignBytes extends ffi.Struct {
  @ffi.Int32()
  external int len;

  external ffi.Pointer<ffi.Uint8> data;
}

final class _UniFfiRustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external _UniFfiRustBuffer errorBuf;
}

const int _uniFfiRustCallStatusSuccess = 0;
const int _uniFfiRustCallStatusError = 1;
const int _uniFfiRustCallStatusUnexpectedError = 2;
const int _uniFfiRustCallStatusCancelled = 3;

const _sentinel = Object();

/// Extraction result containing content, comments, and metadata.
class ExtractResult {
  const ExtractResult({
    required this.contentText,
    required this.commentsText,
    required this.contentHtml,
    required this.commentsHtml,
    required this.metadata,
  });

  final String contentText;
  final String commentsText;
  final String contentHtml;
  final String commentsHtml;
  final Metadata metadata;

  Map<String, dynamic> toJson() {
    return {
      'contentText': this.contentText,
      'commentsText': this.commentsText,
      'contentHtml': this.contentHtml,
      'commentsHtml': this.commentsHtml,
      'metadata': this.metadata.toJson(),
    };
  }

  factory ExtractResult.fromJson(Map<String, dynamic> json) {
    return ExtractResult(
      contentText: json['contentText'] as String,
      commentsText: json['commentsText'] as String,
      contentHtml: json['contentHtml'] as String,
      commentsHtml: json['commentsHtml'] as String,
      metadata: Metadata.fromJson(json['metadata'] as Map<String, dynamic>),
    );
  }

  ExtractResult copyWith({
    String? contentText,
    String? commentsText,
    String? contentHtml,
    String? commentsHtml,
    Metadata? metadata,
  }) {
    return ExtractResult(
      contentText: contentText ?? this.contentText,
      commentsText: commentsText ?? this.commentsText,
      contentHtml: contentHtml ?? this.contentHtml,
      commentsHtml: commentsHtml ?? this.commentsHtml,
      metadata: metadata ?? this.metadata,
    );
  }

  @override
  String toString() {
    return 'ExtractResult(contentText: $contentText, commentsText: $commentsText, contentHtml: $contentHtml, commentsHtml: $commentsHtml, metadata: $metadata)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractResult && contentText == other.contentText && commentsText == other.commentsText && contentHtml == other.contentHtml && commentsHtml == other.commentsHtml && metadata == other.metadata;

  @override
  int get hashCode => Object.hash(contentText, commentsText, contentHtml, commentsHtml, metadata);
}

/// Advanced tuning parameters.
class ExtractionConfig {
  const ExtractionConfig({
    required this.minExtractedSize,
    required this.minExtractedCommentSize,
    required this.minOutputSize,
    required this.minOutputCommentSize,
  });

  final int minExtractedSize;
  final int minExtractedCommentSize;
  final int minOutputSize;
  final int minOutputCommentSize;

  Map<String, dynamic> toJson() {
    return {
      'minExtractedSize': this.minExtractedSize,
      'minExtractedCommentSize': this.minExtractedCommentSize,
      'minOutputSize': this.minOutputSize,
      'minOutputCommentSize': this.minOutputCommentSize,
    };
  }

  factory ExtractionConfig.fromJson(Map<String, dynamic> json) {
    return ExtractionConfig(
      minExtractedSize: (json['minExtractedSize'] as num).toInt(),
      minExtractedCommentSize: (json['minExtractedCommentSize'] as num).toInt(),
      minOutputSize: (json['minOutputSize'] as num).toInt(),
      minOutputCommentSize: (json['minOutputCommentSize'] as num).toInt(),
    );
  }

  ExtractionConfig copyWith({
    int? minExtractedSize,
    int? minExtractedCommentSize,
    int? minOutputSize,
    int? minOutputCommentSize,
  }) {
    return ExtractionConfig(
      minExtractedSize: minExtractedSize ?? this.minExtractedSize,
      minExtractedCommentSize: minExtractedCommentSize ?? this.minExtractedCommentSize,
      minOutputSize: minOutputSize ?? this.minOutputSize,
      minOutputCommentSize: minOutputCommentSize ?? this.minOutputCommentSize,
    );
  }

  @override
  String toString() {
    return 'ExtractionConfig(minExtractedSize: $minExtractedSize, minExtractedCommentSize: $minExtractedCommentSize, minOutputSize: $minOutputSize, minOutputCommentSize: $minOutputCommentSize)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractionConfig && minExtractedSize == other.minExtractedSize && minExtractedCommentSize == other.minExtractedCommentSize && minOutputSize == other.minOutputSize && minOutputCommentSize == other.minOutputCommentSize;

  @override
  int get hashCode => Object.hash(minExtractedSize, minExtractedCommentSize, minOutputSize, minOutputCommentSize);
}

/// Extraction options.
class ExtractionOptions {
  const ExtractionOptions({
    required this.config,
    /// Page URL as string, or empty.
    required this.originalUrl,
    /// ISO 639-1 language code to enforce.
    required this.targetLanguage,
    required this.enableFallback,
    required this.focus,
    required this.excludeComments,
    required this.excludeTables,
    required this.includeImages,
    required this.includeLinks,
    required this.deduplicate,
    required this.requireEssentialMetadata,
    required this.maxTreeSize,
    /// CSS selector for pre-pruning elements.
    required this.pruneSelector,
    required this.htmlDateMode,
    /// Date override as ISO-8601 string (YYYY-MM-DD), or empty.
    required this.htmlDateOverride,
  });

  final ExtractionConfig config;
  /// Page URL as string, or empty.
  final String? originalUrl;
  /// ISO 639-1 language code to enforce.
  final String? targetLanguage;
  final bool enableFallback;
  final ExtractionFocus focus;
  final bool excludeComments;
  final bool excludeTables;
  final bool includeImages;
  final bool includeLinks;
  final bool deduplicate;
  final bool requireEssentialMetadata;
  final int? maxTreeSize;
  /// CSS selector for pre-pruning elements.
  final String? pruneSelector;
  final HtmlDateMode htmlDateMode;
  /// Date override as ISO-8601 string (YYYY-MM-DD), or empty.
  final String? htmlDateOverride;

  Map<String, dynamic> toJson() {
    return {
      'config': this.config.toJson(),
      'originalUrl': this.originalUrl,
      'targetLanguage': this.targetLanguage,
      'enableFallback': this.enableFallback,
      'focus': ExtractionFocusFfiCodec.encode(this.focus),
      'excludeComments': this.excludeComments,
      'excludeTables': this.excludeTables,
      'includeImages': this.includeImages,
      'includeLinks': this.includeLinks,
      'deduplicate': this.deduplicate,
      'requireEssentialMetadata': this.requireEssentialMetadata,
      'maxTreeSize': this.maxTreeSize,
      'pruneSelector': this.pruneSelector,
      'htmlDateMode': HtmlDateModeFfiCodec.encode(this.htmlDateMode),
      'htmlDateOverride': this.htmlDateOverride,
    };
  }

  factory ExtractionOptions.fromJson(Map<String, dynamic> json) {
    return ExtractionOptions(
      config: ExtractionConfig.fromJson(json['config'] as Map<String, dynamic>),
      originalUrl: json['originalUrl'] == null ? null : json['originalUrl'] as String,
      targetLanguage: json['targetLanguage'] == null ? null : json['targetLanguage'] as String,
      enableFallback: json['enableFallback'] as bool,
      focus: ExtractionFocusFfiCodec.decode(json['focus'] as String),
      excludeComments: json['excludeComments'] as bool,
      excludeTables: json['excludeTables'] as bool,
      includeImages: json['includeImages'] as bool,
      includeLinks: json['includeLinks'] as bool,
      deduplicate: json['deduplicate'] as bool,
      requireEssentialMetadata: json['requireEssentialMetadata'] as bool,
      maxTreeSize: json['maxTreeSize'] == null ? null : (json['maxTreeSize'] as num).toInt(),
      pruneSelector: json['pruneSelector'] == null ? null : json['pruneSelector'] as String,
      htmlDateMode: HtmlDateModeFfiCodec.decode(json['htmlDateMode'] as String),
      htmlDateOverride: json['htmlDateOverride'] == null ? null : json['htmlDateOverride'] as String,
    );
  }

  ExtractionOptions copyWith({
    ExtractionConfig? config,
    Object? originalUrl = _sentinel,
    Object? targetLanguage = _sentinel,
    bool? enableFallback,
    ExtractionFocus? focus,
    bool? excludeComments,
    bool? excludeTables,
    bool? includeImages,
    bool? includeLinks,
    bool? deduplicate,
    bool? requireEssentialMetadata,
    Object? maxTreeSize = _sentinel,
    Object? pruneSelector = _sentinel,
    HtmlDateMode? htmlDateMode,
    Object? htmlDateOverride = _sentinel,
  }) {
    return ExtractionOptions(
      config: config ?? this.config,
      originalUrl: originalUrl == _sentinel ? this.originalUrl : originalUrl as String?,
      targetLanguage: targetLanguage == _sentinel ? this.targetLanguage : targetLanguage as String?,
      enableFallback: enableFallback ?? this.enableFallback,
      focus: focus ?? this.focus,
      excludeComments: excludeComments ?? this.excludeComments,
      excludeTables: excludeTables ?? this.excludeTables,
      includeImages: includeImages ?? this.includeImages,
      includeLinks: includeLinks ?? this.includeLinks,
      deduplicate: deduplicate ?? this.deduplicate,
      requireEssentialMetadata: requireEssentialMetadata ?? this.requireEssentialMetadata,
      maxTreeSize: maxTreeSize == _sentinel ? this.maxTreeSize : maxTreeSize as int?,
      pruneSelector: pruneSelector == _sentinel ? this.pruneSelector : pruneSelector as String?,
      htmlDateMode: htmlDateMode ?? this.htmlDateMode,
      htmlDateOverride: htmlDateOverride == _sentinel ? this.htmlDateOverride : htmlDateOverride as String?,
    );
  }

  @override
  String toString() {
    return 'ExtractionOptions(config: $config, originalUrl: $originalUrl, targetLanguage: $targetLanguage, enableFallback: $enableFallback, focus: $focus, excludeComments: $excludeComments, excludeTables: $excludeTables, includeImages: $includeImages, includeLinks: $includeLinks, deduplicate: $deduplicate, requireEssentialMetadata: $requireEssentialMetadata, maxTreeSize: $maxTreeSize, pruneSelector: $pruneSelector, htmlDateMode: $htmlDateMode, htmlDateOverride: $htmlDateOverride)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractionOptions && config == other.config && originalUrl == other.originalUrl && targetLanguage == other.targetLanguage && enableFallback == other.enableFallback && focus == other.focus && excludeComments == other.excludeComments && excludeTables == other.excludeTables && includeImages == other.includeImages && includeLinks == other.includeLinks && deduplicate == other.deduplicate && requireEssentialMetadata == other.requireEssentialMetadata && maxTreeSize == other.maxTreeSize && pruneSelector == other.pruneSelector && htmlDateMode == other.htmlDateMode && htmlDateOverride == other.htmlDateOverride;

  @override
  int get hashCode => Object.hash(config, originalUrl, targetLanguage, enableFallback, focus, excludeComments, excludeTables, includeImages, includeLinks, deduplicate, requireEssentialMetadata, maxTreeSize, pruneSelector, htmlDateMode, htmlDateOverride);
}

/// Document metadata extracted from HTML.
class Metadata {
  const Metadata({
    required this.title,
    required this.author,
    required this.url,
    required this.hostname,
    required this.description,
    required this.sitename,
    /// ISO-8601 date string (YYYY-MM-DD) or empty.
    required this.date,
    required this.categories,
    required this.tags,
    required this.id,
    required this.fingerprint,
    required this.license,
    required this.language,
    required this.image,
    required this.pageType,
  });

  final String title;
  final String author;
  final String url;
  final String hostname;
  final String description;
  final String sitename;
  /// ISO-8601 date string (YYYY-MM-DD) or empty.
  final String? date;
  final List<String> categories;
  final List<String> tags;
  final String id;
  final String fingerprint;
  final String license;
  final String language;
  final String image;
  final String pageType;

  Map<String, dynamic> toJson() {
    return {
      'title': this.title,
      'author': this.author,
      'url': this.url,
      'hostname': this.hostname,
      'description': this.description,
      'sitename': this.sitename,
      'date': this.date,
      'categories': this.categories,
      'tags': this.tags,
      'id': this.id,
      'fingerprint': this.fingerprint,
      'license': this.license,
      'language': this.language,
      'image': this.image,
      'pageType': this.pageType,
    };
  }

  factory Metadata.fromJson(Map<String, dynamic> json) {
    return Metadata(
      title: json['title'] as String,
      author: json['author'] as String,
      url: json['url'] as String,
      hostname: json['hostname'] as String,
      description: json['description'] as String,
      sitename: json['sitename'] as String,
      date: json['date'] == null ? null : json['date'] as String,
      categories: (json['categories'] as List).map((item) => item as String).toList(),
      tags: (json['tags'] as List).map((item) => item as String).toList(),
      id: json['id'] as String,
      fingerprint: json['fingerprint'] as String,
      license: json['license'] as String,
      language: json['language'] as String,
      image: json['image'] as String,
      pageType: json['pageType'] as String,
    );
  }

  Metadata copyWith({
    String? title,
    String? author,
    String? url,
    String? hostname,
    String? description,
    String? sitename,
    Object? date = _sentinel,
    List<String>? categories,
    List<String>? tags,
    String? id,
    String? fingerprint,
    String? license,
    String? language,
    String? image,
    String? pageType,
  }) {
    return Metadata(
      title: title ?? this.title,
      author: author ?? this.author,
      url: url ?? this.url,
      hostname: hostname ?? this.hostname,
      description: description ?? this.description,
      sitename: sitename ?? this.sitename,
      date: date == _sentinel ? this.date : date as String?,
      categories: categories ?? this.categories,
      tags: tags ?? this.tags,
      id: id ?? this.id,
      fingerprint: fingerprint ?? this.fingerprint,
      license: license ?? this.license,
      language: language ?? this.language,
      image: image ?? this.image,
      pageType: pageType ?? this.pageType,
    );
  }

  @override
  String toString() {
    return 'Metadata(title: $title, author: $author, url: $url, hostname: $hostname, description: $description, sitename: $sitename, date: $date, categories: $categories, tags: $tags, id: $id, fingerprint: $fingerprint, license: $license, language: $language, image: $image, pageType: $pageType)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Metadata && title == other.title && author == other.author && url == other.url && hostname == other.hostname && description == other.description && sitename == other.sitename && date == other.date && categories == other.categories && tags == other.tags && id == other.id && fingerprint == other.fingerprint && license == other.license && language == other.language && image == other.image && pageType == other.pageType;

  @override
  int get hashCode => Object.hash(title, author, url, hostname, description, sitename, date, categories, tags, id, fingerprint, license, language, image, pageType);
}

/// Extraction strategy.
enum ExtractionFocus {
  balanced,
  favorRecall,
  favorPrecision,
}

/// Date extraction mode.
enum HtmlDateMode {
  automatic,
  fast,
  extensive,
  disabled,
}

/// Errors returned by extraction functions.
sealed class TrafilaturaError {
  const TrafilaturaError();
}

final class TrafilaturaErrorParseError extends TrafilaturaError {
  const TrafilaturaErrorParseError({
    required this.reason,
  });
  final String reason;

  @override
  String toString() {
    return 'TrafilaturaErrorParseError(reason: $reason)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafilaturaErrorParseError && reason == other.reason;

  @override
  int get hashCode => reason.hashCode;
}

final class TrafilaturaErrorLanguageMismatch extends TrafilaturaError {
  const TrafilaturaErrorLanguageMismatch({
    required this.expected,
    required this.got,
  });
  final String expected;
  final String got;

  @override
  String toString() {
    return 'TrafilaturaErrorLanguageMismatch(expected: $expected, got: $got)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafilaturaErrorLanguageMismatch && expected == other.expected && got == other.got;

  @override
  int get hashCode => Object.hash(expected, got);
}

final class TrafilaturaErrorInsufficientContent extends TrafilaturaError {
  const TrafilaturaErrorInsufficientContent({
    required this.reason,
  });
  final String reason;

  @override
  String toString() {
    return 'TrafilaturaErrorInsufficientContent(reason: $reason)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafilaturaErrorInsufficientContent && reason == other.reason;

  @override
  int get hashCode => reason.hashCode;
}

final class TrafilaturaErrorMissingMetadata extends TrafilaturaError {
  const TrafilaturaErrorMissingMetadata({
    required this.reason,
  });
  final String reason;

  @override
  String toString() {
    return 'TrafilaturaErrorMissingMetadata(reason: $reason)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafilaturaErrorMissingMetadata && reason == other.reason;

  @override
  int get hashCode => reason.hashCode;
}

final class TrafilaturaErrorDuplicateContent extends TrafilaturaError {
  const TrafilaturaErrorDuplicateContent();

  @override
  String toString() {
    return 'TrafilaturaErrorDuplicateContent()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafilaturaErrorDuplicateContent;

  @override
  int get hashCode => runtimeType.hashCode;
}

final class TrafilaturaErrorTreeTooLarge extends TrafilaturaError {
  const TrafilaturaErrorTreeTooLarge({
    required this.size,
  });
  final int size;

  @override
  String toString() {
    return 'TrafilaturaErrorTreeTooLarge(size: $size)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafilaturaErrorTreeTooLarge && size == other.size;

  @override
  int get hashCode => size.hashCode;
}

/// Errors returned by extraction functions.
sealed class TrafilaturaErrorException implements Exception {
  const TrafilaturaErrorException();
}

final class TrafilaturaErrorExceptionParseError extends TrafilaturaErrorException {
  const TrafilaturaErrorExceptionParseError({
    required this.reason,
  });
  final String reason;

  @override
  String toString() {
    return 'TrafilaturaErrorExceptionParseError(reason: $reason)';
  }
}

final class TrafilaturaErrorExceptionLanguageMismatch extends TrafilaturaErrorException {
  const TrafilaturaErrorExceptionLanguageMismatch({
    required this.expected,
    required this.got,
  });
  final String expected;
  final String got;

  @override
  String toString() {
    return 'TrafilaturaErrorExceptionLanguageMismatch(expected: $expected, got: $got)';
  }
}

final class TrafilaturaErrorExceptionInsufficientContent extends TrafilaturaErrorException {
  const TrafilaturaErrorExceptionInsufficientContent({
    required this.reason,
  });
  final String reason;

  @override
  String toString() {
    return 'TrafilaturaErrorExceptionInsufficientContent(reason: $reason)';
  }
}

final class TrafilaturaErrorExceptionMissingMetadata extends TrafilaturaErrorException {
  const TrafilaturaErrorExceptionMissingMetadata({
    required this.reason,
  });
  final String reason;

  @override
  String toString() {
    return 'TrafilaturaErrorExceptionMissingMetadata(reason: $reason)';
  }
}

final class TrafilaturaErrorExceptionDuplicateContent extends TrafilaturaErrorException {
  const TrafilaturaErrorExceptionDuplicateContent();

  @override
  String toString() {
    return 'TrafilaturaErrorExceptionDuplicateContent()';
  }
}

final class TrafilaturaErrorExceptionTreeTooLarge extends TrafilaturaErrorException {
  const TrafilaturaErrorExceptionTreeTooLarge({
    required this.size,
  });
  final int size;

  @override
  String toString() {
    return 'TrafilaturaErrorExceptionTreeTooLarge(size: $size)';
  }
}

TrafilaturaErrorException _uniffiLiftTrafilaturaErrorException(Uint8List bytes) {
  final TrafilaturaError value = _uniffiDecodeTrafilaturaError(bytes);
  if (value is TrafilaturaErrorParseError) {
    return TrafilaturaErrorExceptionParseError(
      reason: value.reason,
    );
  }
  if (value is TrafilaturaErrorLanguageMismatch) {
    return TrafilaturaErrorExceptionLanguageMismatch(
      expected: value.expected,
      got: value.got,
    );
  }
  if (value is TrafilaturaErrorInsufficientContent) {
    return TrafilaturaErrorExceptionInsufficientContent(
      reason: value.reason,
    );
  }
  if (value is TrafilaturaErrorMissingMetadata) {
    return TrafilaturaErrorExceptionMissingMetadata(
      reason: value.reason,
    );
  }
  if (value is TrafilaturaErrorDuplicateContent) return const TrafilaturaErrorExceptionDuplicateContent();
  if (value is TrafilaturaErrorTreeTooLarge) {
    return TrafilaturaErrorExceptionTreeTooLarge(
      size: value.size,
    );
  }
  throw StateError('Unknown TrafilaturaError error variant while lifting exception: $value');
}

String _encodeExtractionFocus(ExtractionFocus value) {
  return switch (value) {
    ExtractionFocus.balanced => 'balanced',
    ExtractionFocus.favorRecall => 'favorRecall',
    ExtractionFocus.favorPrecision => 'favorPrecision',
  };
}

ExtractionFocus _decodeExtractionFocus(String raw) {
  return switch (raw) {
    'balanced' => ExtractionFocus.balanced,
    'favorRecall' => ExtractionFocus.favorRecall,
    'favorPrecision' => ExtractionFocus.favorPrecision,
    _ => throw StateError('Unknown ExtractionFocus variant: $raw'),
  };
}

String _encodeHtmlDateMode(HtmlDateMode value) {
  return switch (value) {
    HtmlDateMode.automatic => 'automatic',
    HtmlDateMode.fast => 'fast',
    HtmlDateMode.extensive => 'extensive',
    HtmlDateMode.disabled => 'disabled',
  };
}

HtmlDateMode _decodeHtmlDateMode(String raw) {
  return switch (raw) {
    'automatic' => HtmlDateMode.automatic,
    'fast' => HtmlDateMode.fast,
    'extensive' => HtmlDateMode.extensive,
    'disabled' => HtmlDateMode.disabled,
    _ => throw StateError('Unknown HtmlDateMode variant: $raw'),
  };
}

String _encodeTrafilaturaError(TrafilaturaError value) {
  if (value is TrafilaturaErrorParseError) {
    return jsonEncode({
      'tag': 'parseError',
      'reason': value.reason,
    });
  }
  if (value is TrafilaturaErrorLanguageMismatch) {
    return jsonEncode({
      'tag': 'languageMismatch',
      'expected': value.expected,
      'got': value.got,
    });
  }
  if (value is TrafilaturaErrorInsufficientContent) {
    return jsonEncode({
      'tag': 'insufficientContent',
      'reason': value.reason,
    });
  }
  if (value is TrafilaturaErrorMissingMetadata) {
    return jsonEncode({
      'tag': 'missingMetadata',
      'reason': value.reason,
    });
  }
  if (value is TrafilaturaErrorDuplicateContent) {
    return jsonEncode({
      'tag': 'duplicateContent',
    });
  }
  if (value is TrafilaturaErrorTreeTooLarge) {
    return jsonEncode({
      'tag': 'treeTooLarge',
      'size': value.size,
    });
  }
  throw StateError('Unknown TrafilaturaError variant instance: $value');
}

TrafilaturaError _decodeTrafilaturaError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'parseError':
      return TrafilaturaErrorParseError(
        reason: map['reason'] as String,
      );
    case 'languageMismatch':
      return TrafilaturaErrorLanguageMismatch(
        expected: map['expected'] as String,
        got: map['got'] as String,
      );
    case 'insufficientContent':
      return TrafilaturaErrorInsufficientContent(
        reason: map['reason'] as String,
      );
    case 'missingMetadata':
      return TrafilaturaErrorMissingMetadata(
        reason: map['reason'] as String,
      );
    case 'duplicateContent':
      return TrafilaturaErrorDuplicateContent(
      );
    case 'treeTooLarge':
      return TrafilaturaErrorTreeTooLarge(
        size: (map['size'] as num).toInt(),
      );
    default:
      throw StateError('Unknown TrafilaturaError variant tag: $tag');
  }
}

String _encodeTrafilaturaErrorException(TrafilaturaErrorException value) {
  if (value is TrafilaturaErrorExceptionParseError) {
    return jsonEncode({
      'tag': 'parseError',
      'reason': value.reason,
    });
  }
  if (value is TrafilaturaErrorExceptionLanguageMismatch) {
    return jsonEncode({
      'tag': 'languageMismatch',
      'expected': value.expected,
      'got': value.got,
    });
  }
  if (value is TrafilaturaErrorExceptionInsufficientContent) {
    return jsonEncode({
      'tag': 'insufficientContent',
      'reason': value.reason,
    });
  }
  if (value is TrafilaturaErrorExceptionMissingMetadata) {
    return jsonEncode({
      'tag': 'missingMetadata',
      'reason': value.reason,
    });
  }
  if (value is TrafilaturaErrorExceptionDuplicateContent) {
    return jsonEncode({
      'tag': 'duplicateContent',
    });
  }
  if (value is TrafilaturaErrorExceptionTreeTooLarge) {
    return jsonEncode({
      'tag': 'treeTooLarge',
      'size': value.size,
    });
  }
  throw StateError('Unknown TrafilaturaErrorException exception instance: $value');
}

TrafilaturaErrorException _decodeTrafilaturaErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'parseError':
      return TrafilaturaErrorExceptionParseError(
        reason: map['reason'] as String,
      );
    case 'languageMismatch':
      return TrafilaturaErrorExceptionLanguageMismatch(
        expected: map['expected'] as String,
        got: map['got'] as String,
      );
    case 'insufficientContent':
      return TrafilaturaErrorExceptionInsufficientContent(
        reason: map['reason'] as String,
      );
    case 'missingMetadata':
      return TrafilaturaErrorExceptionMissingMetadata(
        reason: map['reason'] as String,
      );
    case 'duplicateContent':
      return const TrafilaturaErrorExceptionDuplicateContent();
    case 'treeTooLarge':
      return TrafilaturaErrorExceptionTreeTooLarge(
        size: (map['size'] as num).toInt(),
      );
    default:
      throw StateError('Unknown TrafilaturaErrorException exception tag: $tag');
  }
}

final class ExtractionFocusFfiCodec {
  const ExtractionFocusFfiCodec._();

  static String encode(ExtractionFocus value) => _encodeExtractionFocus(value);

  static ExtractionFocus decode(String raw) => _decodeExtractionFocus(raw);
}

final class HtmlDateModeFfiCodec {
  const HtmlDateModeFfiCodec._();

  static String encode(HtmlDateMode value) => _encodeHtmlDateMode(value);

  static HtmlDateMode decode(String raw) => _decodeHtmlDateMode(raw);
}

final class TrafilaturaErrorFfiCodec {
  const TrafilaturaErrorFfiCodec._();

  static String encode(TrafilaturaError value) => _encodeTrafilaturaError(value);

  static TrafilaturaError decode(String raw) => _decodeTrafilaturaError(raw);
}

final class TrafilaturaErrorExceptionFfiCodec {
  const TrafilaturaErrorExceptionFfiCodec._();

  static String encode(TrafilaturaErrorException value) => _encodeTrafilaturaErrorException(value);

  static TrafilaturaErrorException decode(Object? raw) => _decodeTrafilaturaErrorException(raw);
}

final class _UniFfiBinaryWriter {
  final BytesBuilder _builder = BytesBuilder(copy: false);

  void writeU8(int value) => _builder.add([value & 0xFF]);
  void writeI8(int value) => _builder.add([(value) & 0xFF]);
  void writeU16(int value) {
    final data = ByteData(2)..setUint16(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI16(int value) {
    final data = ByteData(2)..setInt16(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeU32(int value) {
    final data = ByteData(4)..setUint32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI32(int value) {
    final data = ByteData(4)..setInt32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeU64(int value) {
    final data = ByteData(8)..setUint64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI64(int value) {
    final data = ByteData(8)..setInt64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeF32(double value) {
    final data = ByteData(4)..setFloat32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeF64(double value) {
    final data = ByteData(8)..setFloat64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeBool(bool value) => writeI8(value ? 1 : 0);
  void writeBytes(Uint8List bytes) => _builder.add(bytes);
  void writeString(String value) {
    final bytes = Uint8List.fromList(utf8.encode(value));
    writeI32(bytes.length);
    writeBytes(bytes);
  }

  Uint8List toBytes() => _builder.takeBytes();
}

final class _UniFfiBinaryReader {
  _UniFfiBinaryReader(this._bytes);
  final Uint8List _bytes;
  int _offset = 0;

  bool get isDone => _offset == _bytes.length;

  ByteData _readData(int len) {
    if (_offset + len > _bytes.length) {
      throw StateError('buffer underflow while decoding UniFFI payload');
    }
    final data = ByteData.sublistView(_bytes, _offset, _offset + len);
    _offset += len;
    return data;
  }

  int readU8() => _readData(1).getUint8(0);
  int readI8() => _readData(1).getInt8(0);
  int readU16() => _readData(2).getUint16(0, Endian.big);
  int readI16() => _readData(2).getInt16(0, Endian.big);
  int readU32() => _readData(4).getUint32(0, Endian.big);
  int readI32() => _readData(4).getInt32(0, Endian.big);
  int readU64() => _readData(8).getUint64(0, Endian.big);
  int readI64() => _readData(8).getInt64(0, Endian.big);
  double readF32() => _readData(4).getFloat32(0, Endian.big);
  double readF64() => _readData(8).getFloat64(0, Endian.big);
  bool readBool() {
    final value = readI8();
    if (value == 0) return false;
    if (value == 1) return true;
    throw StateError('invalid boolean payload value: $value');
  }
  Uint8List readBytes(int len) {
    if (_offset + len > _bytes.length) {
      throw StateError('buffer underflow while decoding UniFFI payload bytes');
    }
    final out = Uint8List.fromList(_bytes.sublist(_offset, _offset + len));
    _offset += len;
    return out;
  }
  String readString() {
    final len = readI32();
    if (len < 0) {
      throw StateError('invalid string length in UniFFI payload: $len');
    }
    return utf8.decode(readBytes(len));
  }
}

void _uniffiWriteExtractResult(ExtractResult value, _UniFfiBinaryWriter writer) {
  writer.writeString(value.contentText);
  writer.writeString(value.commentsText);
  writer.writeString(value.contentHtml);
  writer.writeString(value.commentsHtml);
  _uniffiWriteMetadata(value.metadata, writer);
}

Uint8List _uniffiEncodeExtractResult(ExtractResult value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteExtractResult(value, writer);
  return writer.toBytes();
}

ExtractResult _uniffiReadExtractResult(_UniFfiBinaryReader reader) {
  return ExtractResult(
    contentText: reader.readString(),
    commentsText: reader.readString(),
    contentHtml: reader.readString(),
    commentsHtml: reader.readString(),
    metadata: _uniffiReadMetadata(reader),
  );
}

ExtractResult _uniffiDecodeExtractResult(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadExtractResult(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding ExtractResult');
  }
  return value;
}

void _uniffiWriteExtractionConfig(ExtractionConfig value, _UniFfiBinaryWriter writer) {
  writer.writeI64(value.minExtractedSize);
  writer.writeI64(value.minExtractedCommentSize);
  writer.writeI64(value.minOutputSize);
  writer.writeI64(value.minOutputCommentSize);
}

Uint8List _uniffiEncodeExtractionConfig(ExtractionConfig value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteExtractionConfig(value, writer);
  return writer.toBytes();
}

ExtractionConfig _uniffiReadExtractionConfig(_UniFfiBinaryReader reader) {
  return ExtractionConfig(
    minExtractedSize: reader.readI64(),
    minExtractedCommentSize: reader.readI64(),
    minOutputSize: reader.readI64(),
    minOutputCommentSize: reader.readI64(),
  );
}

ExtractionConfig _uniffiDecodeExtractionConfig(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadExtractionConfig(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding ExtractionConfig');
  }
  return value;
}

void _uniffiWriteExtractionOptions(ExtractionOptions value, _UniFfiBinaryWriter writer) {
  _uniffiWriteExtractionConfig(value.config, writer);
  if (value.originalUrl == null) {
    writer.writeI8(0);
  } else {
    writer.writeI8(1);
    writer.writeString(value.originalUrl!);
  }
  if (value.targetLanguage == null) {
    writer.writeI8(0);
  } else {
    writer.writeI8(1);
    writer.writeString(value.targetLanguage!);
  }
  writer.writeBool(value.enableFallback);
  _uniffiWriteExtractionFocus(value.focus, writer);
  writer.writeBool(value.excludeComments);
  writer.writeBool(value.excludeTables);
  writer.writeBool(value.includeImages);
  writer.writeBool(value.includeLinks);
  writer.writeBool(value.deduplicate);
  writer.writeBool(value.requireEssentialMetadata);
  if (value.maxTreeSize == null) {
    writer.writeI8(0);
  } else {
    writer.writeI8(1);
    writer.writeI64(value.maxTreeSize!);
  }
  if (value.pruneSelector == null) {
    writer.writeI8(0);
  } else {
    writer.writeI8(1);
    writer.writeString(value.pruneSelector!);
  }
  _uniffiWriteHtmlDateMode(value.htmlDateMode, writer);
  if (value.htmlDateOverride == null) {
    writer.writeI8(0);
  } else {
    writer.writeI8(1);
    writer.writeString(value.htmlDateOverride!);
  }
}

Uint8List _uniffiEncodeExtractionOptions(ExtractionOptions value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteExtractionOptions(value, writer);
  return writer.toBytes();
}

ExtractionOptions _uniffiReadExtractionOptions(_UniFfiBinaryReader reader) {
  return ExtractionOptions(
    config: _uniffiReadExtractionConfig(reader),
    originalUrl: (() { final int __tag = reader.readI8(); if (__tag == 0) return null; if (__tag != 1) throw StateError('invalid optional tag: $__tag'); return reader.readString(); })(),
    targetLanguage: (() { final int __tag = reader.readI8(); if (__tag == 0) return null; if (__tag != 1) throw StateError('invalid optional tag: $__tag'); return reader.readString(); })(),
    enableFallback: reader.readBool(),
    focus: _uniffiReadExtractionFocus(reader),
    excludeComments: reader.readBool(),
    excludeTables: reader.readBool(),
    includeImages: reader.readBool(),
    includeLinks: reader.readBool(),
    deduplicate: reader.readBool(),
    requireEssentialMetadata: reader.readBool(),
    maxTreeSize: (() { final int __tag = reader.readI8(); if (__tag == 0) return null; if (__tag != 1) throw StateError('invalid optional tag: $__tag'); return reader.readI64(); })(),
    pruneSelector: (() { final int __tag = reader.readI8(); if (__tag == 0) return null; if (__tag != 1) throw StateError('invalid optional tag: $__tag'); return reader.readString(); })(),
    htmlDateMode: _uniffiReadHtmlDateMode(reader),
    htmlDateOverride: (() { final int __tag = reader.readI8(); if (__tag == 0) return null; if (__tag != 1) throw StateError('invalid optional tag: $__tag'); return reader.readString(); })(),
  );
}

ExtractionOptions _uniffiDecodeExtractionOptions(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadExtractionOptions(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding ExtractionOptions');
  }
  return value;
}

void _uniffiWriteMetadata(Metadata value, _UniFfiBinaryWriter writer) {
  writer.writeString(value.title);
  writer.writeString(value.author);
  writer.writeString(value.url);
  writer.writeString(value.hostname);
  writer.writeString(value.description);
  writer.writeString(value.sitename);
  if (value.date == null) {
    writer.writeI8(0);
  } else {
    writer.writeI8(1);
    writer.writeString(value.date!);
  }
  writer.writeI32(value.categories.length);
  for (final item in value.categories) {
    writer.writeString(item);
  }
  writer.writeI32(value.tags.length);
  for (final item in value.tags) {
    writer.writeString(item);
  }
  writer.writeString(value.id);
  writer.writeString(value.fingerprint);
  writer.writeString(value.license);
  writer.writeString(value.language);
  writer.writeString(value.image);
  writer.writeString(value.pageType);
}

Uint8List _uniffiEncodeMetadata(Metadata value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteMetadata(value, writer);
  return writer.toBytes();
}

Metadata _uniffiReadMetadata(_UniFfiBinaryReader reader) {
  return Metadata(
    title: reader.readString(),
    author: reader.readString(),
    url: reader.readString(),
    hostname: reader.readString(),
    description: reader.readString(),
    sitename: reader.readString(),
    date: (() { final int __tag = reader.readI8(); if (__tag == 0) return null; if (__tag != 1) throw StateError('invalid optional tag: $__tag'); return reader.readString(); })(),
    categories: (() { final int __len = reader.readI32(); final out = <String>[]; for (var i = 0; i < __len; i++) { out.add(reader.readString()); } return out; })(),
    tags: (() { final int __len = reader.readI32(); final out = <String>[]; for (var i = 0; i < __len; i++) { out.add(reader.readString()); } return out; })(),
    id: reader.readString(),
    fingerprint: reader.readString(),
    license: reader.readString(),
    language: reader.readString(),
    image: reader.readString(),
    pageType: reader.readString(),
  );
}

Metadata _uniffiDecodeMetadata(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadMetadata(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding Metadata');
  }
  return value;
}

void _uniffiWriteExtractionFocus(ExtractionFocus value, _UniFfiBinaryWriter writer) {
  final int tag = switch (value) {
    ExtractionFocus.balanced => 1,
    ExtractionFocus.favorRecall => 2,
    ExtractionFocus.favorPrecision => 3,
  };
  writer.writeI32(tag);
}

Uint8List _uniffiEncodeExtractionFocus(ExtractionFocus value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteExtractionFocus(value, writer);
  return writer.toBytes();
}

ExtractionFocus _uniffiReadExtractionFocus(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return ExtractionFocus.balanced;
    case 2:
      return ExtractionFocus.favorRecall;
    case 3:
      return ExtractionFocus.favorPrecision;
    default:
      throw StateError('Unknown ExtractionFocus variant tag: $tag');
  }
}

ExtractionFocus _uniffiDecodeExtractionFocus(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadExtractionFocus(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding ExtractionFocus');
  }
  return value;
}

void _uniffiWriteHtmlDateMode(HtmlDateMode value, _UniFfiBinaryWriter writer) {
  final int tag = switch (value) {
    HtmlDateMode.automatic => 1,
    HtmlDateMode.fast => 2,
    HtmlDateMode.extensive => 3,
    HtmlDateMode.disabled => 4,
  };
  writer.writeI32(tag);
}

Uint8List _uniffiEncodeHtmlDateMode(HtmlDateMode value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteHtmlDateMode(value, writer);
  return writer.toBytes();
}

HtmlDateMode _uniffiReadHtmlDateMode(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return HtmlDateMode.automatic;
    case 2:
      return HtmlDateMode.fast;
    case 3:
      return HtmlDateMode.extensive;
    case 4:
      return HtmlDateMode.disabled;
    default:
      throw StateError('Unknown HtmlDateMode variant tag: $tag');
  }
}

HtmlDateMode _uniffiDecodeHtmlDateMode(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadHtmlDateMode(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding HtmlDateMode');
  }
  return value;
}

void _uniffiWriteTrafilaturaError(TrafilaturaError value, _UniFfiBinaryWriter writer) {
  if (value is TrafilaturaErrorParseError) {
    writer.writeI32(1);
    writer.writeString(value.reason);
  }
  else if (value is TrafilaturaErrorLanguageMismatch) {
    writer.writeI32(2);
    writer.writeString(value.expected);
    writer.writeString(value.got);
  }
  else if (value is TrafilaturaErrorInsufficientContent) {
    writer.writeI32(3);
    writer.writeString(value.reason);
  }
  else if (value is TrafilaturaErrorMissingMetadata) {
    writer.writeI32(4);
    writer.writeString(value.reason);
  }
  else if (value is TrafilaturaErrorDuplicateContent) {
    writer.writeI32(5);
  }
  else if (value is TrafilaturaErrorTreeTooLarge) {
    writer.writeI32(6);
    writer.writeI64(value.size);
  }
  else {
    throw StateError('Unknown TrafilaturaError variant instance: $value');
  }
}

Uint8List _uniffiEncodeTrafilaturaError(TrafilaturaError value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteTrafilaturaError(value, writer);
  return writer.toBytes();
}

TrafilaturaError _uniffiReadTrafilaturaError(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return TrafilaturaErrorParseError(
        reason: reader.readString(),
      );
    case 2:
      return TrafilaturaErrorLanguageMismatch(
        expected: reader.readString(),
        got: reader.readString(),
      );
    case 3:
      return TrafilaturaErrorInsufficientContent(
        reason: reader.readString(),
      );
    case 4:
      return TrafilaturaErrorMissingMetadata(
        reason: reader.readString(),
      );
    case 5:
      return const TrafilaturaErrorDuplicateContent();
    case 6:
      return TrafilaturaErrorTreeTooLarge(
        size: reader.readI64(),
      );
    default:
      throw StateError('Unknown TrafilaturaError variant tag: $tag');
  }
}

TrafilaturaError _uniffiDecodeTrafilaturaError(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadTrafilaturaError(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding TrafilaturaError');
  }
  return value;
}

class TrafilaturaUniffiFfi {
  TrafilaturaUniffiFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'trafilatura_uniffi';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_trafilatura_uniffi_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_trafilatura_uniffi_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_trafilatura_uniffi_checksum_func_create_readable_document;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_trafilatura_uniffi_checksum_func_create_readable_document');
      _checksum_uniffi_trafilatura_uniffi_checksum_func_create_readable_document = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_trafilatura_uniffi_checksum_func_create_readable_document`: $err');
    }
    if (_checksum_uniffi_trafilatura_uniffi_checksum_func_create_readable_document != 55663) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_trafilatura_uniffi_checksum_func_create_readable_document`: expected 55663, got $_checksum_uniffi_trafilatura_uniffi_checksum_func_create_readable_document');
    }
    final int _checksum_uniffi_trafilatura_uniffi_checksum_func_default_config;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_trafilatura_uniffi_checksum_func_default_config');
      _checksum_uniffi_trafilatura_uniffi_checksum_func_default_config = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_trafilatura_uniffi_checksum_func_default_config`: $err');
    }
    if (_checksum_uniffi_trafilatura_uniffi_checksum_func_default_config != 29638) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_trafilatura_uniffi_checksum_func_default_config`: expected 29638, got $_checksum_uniffi_trafilatura_uniffi_checksum_func_default_config');
    }
    final int _checksum_uniffi_trafilatura_uniffi_checksum_func_default_options;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_trafilatura_uniffi_checksum_func_default_options');
      _checksum_uniffi_trafilatura_uniffi_checksum_func_default_options = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_trafilatura_uniffi_checksum_func_default_options`: $err');
    }
    if (_checksum_uniffi_trafilatura_uniffi_checksum_func_default_options != 23313) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_trafilatura_uniffi_checksum_func_default_options`: expected 23313, got $_checksum_uniffi_trafilatura_uniffi_checksum_func_default_options');
    }
    final int _checksum_uniffi_trafilatura_uniffi_checksum_func_extract;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_trafilatura_uniffi_checksum_func_extract');
      _checksum_uniffi_trafilatura_uniffi_checksum_func_extract = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_trafilatura_uniffi_checksum_func_extract`: $err');
    }
    if (_checksum_uniffi_trafilatura_uniffi_checksum_func_extract != 58272) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_trafilatura_uniffi_checksum_func_extract`: expected 58272, got $_checksum_uniffi_trafilatura_uniffi_checksum_func_extract');
    }
    final int _checksum_uniffi_trafilatura_uniffi_checksum_func_extract_simple;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_trafilatura_uniffi_checksum_func_extract_simple');
      _checksum_uniffi_trafilatura_uniffi_checksum_func_extract_simple = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_trafilatura_uniffi_checksum_func_extract_simple`: $err');
    }
    if (_checksum_uniffi_trafilatura_uniffi_checksum_func_extract_simple != 21108) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_trafilatura_uniffi_checksum_func_extract_simple`: expected 21108, got $_checksum_uniffi_trafilatura_uniffi_checksum_func_extract_simple');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final _UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _uniFfiRustBufferFromBytes = _lib.lookupFunction<_UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus), _UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_trafilatura_uniffi_rustbuffer_from_bytes');
  late final void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _uniFfiRustBufferFree = _lib.lookupFunction<ffi.Void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus), void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_trafilatura_uniffi_rustbuffer_free');

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _createReadableDocumentFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_trafilatura_uniffi_fn_func_create_readable_document');

  String createReadableDocument(ExtractResult result) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List resultBytes = _uniffiEncodeExtractResult(result);
      final ffi.Pointer<ffi.Uint8> resultPtr = resultBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(resultBytes.length);
      if (resultBytes.isNotEmpty) { resultPtr.asTypedList(resultBytes.length).setAll(0, resultBytes); }
      foreignArgPtrs.add(resultPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> resultFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      resultFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      resultFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> resultForeignPtr = calloc<_UniFfiForeignBytes>();
      resultForeignPtr.ref
        ..len = resultBytes.length
        ..data = resultPtr;
      final _UniFfiRustBuffer resultRustBuffer = _uniFfiRustBufferFromBytes(resultForeignPtr.ref, resultFromBytesStatusPtr);
      calloc.free(resultForeignPtr);
      final int resultFromBytesCode = resultFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer resultFromBytesErrBuf = resultFromBytesStatusPtr.ref.errorBuf;
      calloc.free(resultFromBytesStatusPtr);
      if (resultFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> resultFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        resultFromBytesErrBufPtr.ref
          ..capacity = resultFromBytesErrBuf.capacity
          ..len = resultFromBytesErrBuf.len
          ..data = resultFromBytesErrBuf.data;
        rustRetBufferPtrs.add(resultFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $resultFromBytesCode');
      }
      (argBuf + 0).ref.u64 = resultRustBuffer.capacity;
      (argBuf + 1).ref.u64 = resultRustBuffer.len;
      (argBuf + 2).ref.ptr = resultRustBuffer.data.cast<ffi.Void>();
      _createReadableDocumentFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = utf8.decode(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _defaultConfigFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_trafilatura_uniffi_fn_func_default_config');

  ExtractionConfig defaultConfig() {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(0);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      _defaultConfigFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeExtractionConfig(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _defaultOptionsFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_trafilatura_uniffi_fn_func_default_options');

  ExtractionOptions defaultOptions() {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(0);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      _defaultOptionsFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeExtractionOptions(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _extractFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_trafilatura_uniffi_fn_func_extract');

  ExtractResult extract(String html, ExtractionOptions options) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(6);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List htmlBytes = Uint8List.fromList(utf8.encode(html));
      final ffi.Pointer<ffi.Uint8> htmlPtr = htmlBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(htmlBytes.length);
      if (htmlBytes.isNotEmpty) { htmlPtr.asTypedList(htmlBytes.length).setAll(0, htmlBytes); }
      foreignArgPtrs.add(htmlPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> htmlFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      htmlFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      htmlFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> htmlForeignPtr = calloc<_UniFfiForeignBytes>();
      htmlForeignPtr.ref
        ..len = htmlBytes.length
        ..data = htmlPtr;
      final _UniFfiRustBuffer htmlRustBuffer = _uniFfiRustBufferFromBytes(htmlForeignPtr.ref, htmlFromBytesStatusPtr);
      calloc.free(htmlForeignPtr);
      final int htmlFromBytesCode = htmlFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer htmlFromBytesErrBuf = htmlFromBytesStatusPtr.ref.errorBuf;
      calloc.free(htmlFromBytesStatusPtr);
      if (htmlFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> htmlFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        htmlFromBytesErrBufPtr.ref
          ..capacity = htmlFromBytesErrBuf.capacity
          ..len = htmlFromBytesErrBuf.len
          ..data = htmlFromBytesErrBuf.data;
        rustRetBufferPtrs.add(htmlFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $htmlFromBytesCode');
      }
      (argBuf + 0).ref.u64 = htmlRustBuffer.capacity;
      (argBuf + 1).ref.u64 = htmlRustBuffer.len;
      (argBuf + 2).ref.ptr = htmlRustBuffer.data.cast<ffi.Void>();
      final Uint8List optionsBytes = _uniffiEncodeExtractionOptions(options);
      final ffi.Pointer<ffi.Uint8> optionsPtr = optionsBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(optionsBytes.length);
      if (optionsBytes.isNotEmpty) { optionsPtr.asTypedList(optionsBytes.length).setAll(0, optionsBytes); }
      foreignArgPtrs.add(optionsPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> optionsFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      optionsFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      optionsFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> optionsForeignPtr = calloc<_UniFfiForeignBytes>();
      optionsForeignPtr.ref
        ..len = optionsBytes.length
        ..data = optionsPtr;
      final _UniFfiRustBuffer optionsRustBuffer = _uniFfiRustBufferFromBytes(optionsForeignPtr.ref, optionsFromBytesStatusPtr);
      calloc.free(optionsForeignPtr);
      final int optionsFromBytesCode = optionsFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer optionsFromBytesErrBuf = optionsFromBytesStatusPtr.ref.errorBuf;
      calloc.free(optionsFromBytesStatusPtr);
      if (optionsFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> optionsFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        optionsFromBytesErrBufPtr.ref
          ..capacity = optionsFromBytesErrBuf.capacity
          ..len = optionsFromBytesErrBuf.len
          ..data = optionsFromBytesErrBuf.data;
        rustRetBufferPtrs.add(optionsFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $optionsFromBytesCode');
      }
      (argBuf + 3).ref.u64 = optionsRustBuffer.capacity;
      (argBuf + 4).ref.u64 = optionsRustBuffer.len;
      (argBuf + 5).ref.ptr = optionsRustBuffer.data.cast<ffi.Void>();
      _extractFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftTrafilaturaErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeExtractResult(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _extractSimpleFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_trafilatura_uniffi_fn_func_extract_simple');

  ExtractResult extractSimple(String html) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List htmlBytes = Uint8List.fromList(utf8.encode(html));
      final ffi.Pointer<ffi.Uint8> htmlPtr = htmlBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(htmlBytes.length);
      if (htmlBytes.isNotEmpty) { htmlPtr.asTypedList(htmlBytes.length).setAll(0, htmlBytes); }
      foreignArgPtrs.add(htmlPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> htmlFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      htmlFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      htmlFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> htmlForeignPtr = calloc<_UniFfiForeignBytes>();
      htmlForeignPtr.ref
        ..len = htmlBytes.length
        ..data = htmlPtr;
      final _UniFfiRustBuffer htmlRustBuffer = _uniFfiRustBufferFromBytes(htmlForeignPtr.ref, htmlFromBytesStatusPtr);
      calloc.free(htmlForeignPtr);
      final int htmlFromBytesCode = htmlFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer htmlFromBytesErrBuf = htmlFromBytesStatusPtr.ref.errorBuf;
      calloc.free(htmlFromBytesStatusPtr);
      if (htmlFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> htmlFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        htmlFromBytesErrBufPtr.ref
          ..capacity = htmlFromBytesErrBuf.capacity
          ..len = htmlFromBytesErrBuf.len
          ..data = htmlFromBytesErrBuf.data;
        rustRetBufferPtrs.add(htmlFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $htmlFromBytesCode');
      }
      (argBuf + 0).ref.u64 = htmlRustBuffer.capacity;
      (argBuf + 1).ref.u64 = htmlRustBuffer.len;
      (argBuf + 2).ref.ptr = htmlRustBuffer.data.cast<ffi.Void>();
      _extractSimpleFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftTrafilaturaErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeExtractResult(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }
}

TrafilaturaUniffiFfi? _defaultBindings;

TrafilaturaUniffiFfi _bindings() => _defaultBindings ??= TrafilaturaUniffiFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = TrafilaturaUniffiFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

/// Create a self-contained HTML document from an extraction result.
String createReadableDocument(ExtractResult result) {
  return _bindings().createReadableDocument(result);
}

/// Returns the default extraction config.
ExtractionConfig defaultConfig() {
  return _bindings().defaultConfig();
}

/// Returns the default extraction options.
ExtractionOptions defaultOptions() {
  return _bindings().defaultOptions();
}

/// Extract content from HTML with custom options.
ExtractResult extract(String html, ExtractionOptions options) {
  return _bindings().extract(html, options);
}

/// Extract content from HTML with default options.
ExtractResult extractSimple(String html) {
  return _bindings().extractSimple(html);
}

