[package]
name = "trafilatura-uniffi"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "trafilatura_uniffi"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
required-features = ["cli"]

[[bin]]
name = "uniffi-bindgen-dart"
path = "uniffi-bindgen-dart.rs"
required-features = ["dart-cli"]

[[bin]]
name = "uniffi-bindgen-js"
path = "uniffi-bindgen-js.rs"
required-features = ["js-cli"]

[features]
cli = ["uniffi/cli"]
dart-cli = ["dep:uniffi-bindgen-dart"]
js-cli = ["dep:uniffi-bindgen-js", "dep:clap"]

[dependencies]
uniffi = { version = "0.31", features = ["scaffolding-ffi-buffer-fns"] }
thiserror = "2"
trafilatura = { path = ".." }
url = "2"
chrono = "0.4"
uniffi-bindgen-dart = { version = "0.1.3", optional = true }
uniffi-bindgen-js = { path = "/Users/nchapman/Code/uniffi-bindgen-js/crates/ubjs_bindgen", optional = true }
clap = { version = "4", features = ["derive"], optional = true }
