[bindings.swift]
module_name = "Trafilatura"
ffi_module_name = "TrafilaturaFFI"
ffi_module_filename = "TrafilaturaFFI"
cdylib_name = "trafilatura_uniffi"

[bindings.kotlin]
package_name = "trafilatura"
cdylib_name = "trafilatura_uniffi"

[bindings.ruby]
cdylib_name = "trafilatura_uniffi"

[bindings.csharp]
namespace = "trafilatura"
cdylib_name = "trafilatura_uniffi"
